from django.db import models

# Create your models here.
class bannerSlide(models.Model):
    bannerID = models.CharField(max_length=10,primary_key=True)
    bannerTitle = models.CharField(max_length=100)
    bannerUrl = models.CharField(max_length=1000)
    linkTo = models.CharField(max_length=1000)
    sortOrder = models.IntegerField()
    inActive = models.BooleanField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class employee(models.Model):
    employeeID = models.CharField(max_length=10,primary_key=True)
    employeeCode = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    fullName = models.CharField(max_length=100)
    officeEmail = models.CharField(max_length=100)
    jobPositionName = models.CharField(max_length=100)
    organizationUnitName = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    organizationUnitID = models.CharField(max_length=100)
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class employeeInRoles(models.Model):
    employeeID = models.CharField(max_length=100,primary_key=True)
    roleID = models.CharField(max_length=100)
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class employeePermission(models.Model):
    employeePermissionMappingID = models.CharField(max_length=100,primary_key=True)
    employeeID = models.CharField(max_length=100)
    regisPermissionForSubSystemID = models.CharField(max_length=100)
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class event(models.Model):
    eventID = models.CharField(max_length=100,primary_key=True)
    eventName = models.CharField(max_length=100)
    banner = models.CharField(max_length=100)
    bannerMobile = models.CharField(max_length=100)
    avatar = models.CharField(max_length=100)
    topic = models.CharField(max_length=100)
    eventType = models.CharField(max_length=100)
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    cost = models.CharField(max_length=100)
    summary = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    benefitContent = models.CharField(max_length=100)
    organizationUnit = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    slot = models.CharField(max_length=100)
    targetCustomer = models.CharField(max_length=100)
    schedule = models.CharField(max_length=100)
    aiMarketingCode = models.CharField(max_length=100)
    zaloLink = models.CharField(max_length=100)
    fanpageLink = models.CharField(max_length=100)
    videoLink = models.CharField(max_length=100)
    documentLink = models.CharField(max_length=100)
    speaker = models.CharField(max_length=100)
    isHideBanner = models.BooleanField()
    isHideContent = models.BooleanField()
    isHideSchedule = models.BooleanField()
    inActive = models.BooleanField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class leadScoring(models.Model):
    email = models.CharField(max_length=100)
    fullName = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    career = models.CharField(max_length=100)
    scale = models.CharField(max_length=100)
    doSurvey = models.BooleanField()
    openMailNumber = models.IntegerField()
    visitNumber = models.IntegerField()
    downloadNumber = models.IntegerField()
    seminarRegisterNumber = models.IntegerField()
    seminarVisitNumber = models.IntegerField()
    trialNumber = models.IntegerField()
    advisoryNumber = models.IntegerField()
    newsLetterNumber = models.IntegerField()
    messengerInteraction = models.IntegerField()
    ACT_Topic = models.CharField(max_length=100)
    CRM_Topic = models.CharField(max_length=100)
    HRM_Topic = models.CharField(max_length=100)
    BIL_Topic = models.CharField(max_length=100)
    RTl_Topic = models.CharField(max_length=100)
    MGM_Topic = models.CharField(max_length=100)
    Lead_Scoring = models.IntegerField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class logs(models.Model):
    ID = models.CharField(max_length=100,primary_key=True)
    logType = models.CharField(max_length=100)
    logMessage = models.CharField(max_length=100)
    createdDate = models.DateTimeField()

class permission(models.Model):
    permissionID = models.CharField(max_length=100,primary_key=True)
    permissionName = models.CharField(max_length=100)
    permissionCode = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    sortOrder = models.IntegerField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class regisPermissionForSubSystem(models.Model):
    regisPermissionForSubSystemID = models.CharField(max_length=100,primary_key=True)
    permissionID = models.CharField(max_length=100)
    subSystemID = models.CharField(max_length=100)
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class roles(models.Model):
    roleID = models.CharField(max_length=100,primary_key=True)
    roleName = models.CharField(max_length=100)
    roleCode = models.CharField(max_length=100)
    roleLevel = models.IntegerField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class speaker(models.Model):
    speakerID = models.CharField(max_length=100,primary_key=True)
    speakerName = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    avatar = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    inActive = models.BooleanField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class subSystem(models.Model):
    subSystemID = models.CharField(max_length=100,primary_key=True)
    applicationCode = models.CharField(max_length=100)
    subSystemName = models.CharField(max_length=100)
    subSystemCode = models.CharField(max_length=100)
    parentSubSystemCode = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    sortOrder = models.IntegerField()
    createdDate = models.DateTimeField()
    modifiedDate = models.DateTimeField()
    createdBy = models.CharField(max_length=100)
    modifiedBy = models.CharField(max_length=100)

class user(models.Model):
    userID = models.CharField(max_length=100,primary_key=True)
    eventID = models.CharField(max_length=100)
    fullName = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    organizational = models.CharField(max_length=100)
    taxCode = models.CharField(max_length=100)
    createdDate = models.DateTimeField()